/* config.h.  Generated by configure.  */
/* config.hin.  Generated from configure.ac by autoheader.  */

/*@ -macroconstdecl@*/

/* The directory where Splint's library files live */
#define DEFAULT_LARCHPATH ".;C:/splint-3.1.2/lib"

/* Splint's imports directory */
#define DEFAULT_LCLIMPORTDIR ".;C:/splint-3.1.2/imports"

/* system include directory */
#define GCC_INCLUDE_DIR "C:/include"

/* alternate include directory */
#define GCC_INCLUDE_DIR2 "C:/local/include"

/* String describing who compiled this binary and how */
#define LCL_COMPILE "Compiled using Microsoft Visual Studio 2008"

/* Splint's version number */
#define LCL_PARSE_VERSION "Splint 3.1.2"

/* Define to disable support LCL files */
/* #undef NOLCL */

/* Splint's version number and configure/build date */
#define SPLINT_VERSION "Splint 3.1.2 --- 25 Aug 2010"

/* The system's main include directory */
#define SYSTEM_LIBDIR "C:/INCLUDE"

/* target_cpu */
#define TARGET_CPU "x86"

/* uname output */
#define UNAME "WIN32"

/* Define if you're on a Unixy system */
//#define UNIX 0

/* Define to 1 if `lex' declares `yytext' as a `char *' by default, not a
   `char[]'. */
#define YYTEXT_POINTER 1

/* needed to expose mode_t on some machines */
/* #undef _ALL_SOURCE */

/*@ =macroconstdecl@*/
